version: '3.7'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=casting_user
      - POSTGRES_PASSWORD=casting_user
      - POSTGRES_DB=casting_dev

volumes:
  postgres_data: