# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: python:3.8.1-slim-buster
        environment:
          APP_SETTINGS: config.DevelopmentConfig
          DATABASE_URL: postgresql:///castingapi
          AUTH0_DOMAIN: dev-hrmvva9b.us.auth0.com
          ALGORITHMS: RS256
          API_AUDIENCE: casting
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: casting_user
          POSTGRES_PASSWORD: casting_user
          POSTGRES_DB: casting_dev
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y netcat
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            createdb castingapi
            python manage.py db init
            python manage.py db migragte
            python manage.py db upgrade
            python3 test_case.py
workflows:
  # Name the workflow "welcome"
  simple_workflows:
    jobs:
      - build
