# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8.1-slim-buster
        environment:
          APP_SETTINGS: config.DevelopmentConfig
          DATABASE_URL: postgresql://root:casting@localhost/castingapi_test
          AUTH0_DOMAIN: dev-hrmvva9b.us.auth0.com
          ALGORITHMS: RS256
          API_AUDIENCE: casting
      - image: postgres:12-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: "casting"
          POSTGRES_DB: castingapi_test
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: |
            apt-get update
            pip3 install --upgrade pip
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: populate test cases
          command: |
            . venv/bin/activate
            python3 manage.py db upgrade
            python3 test_case.py
      - run:
          name: test by tokens
          command: |
            . venv/bin/activate
            python3 test_app_by_assistant_token.py
            python3 test_app_by_director_token.py
            python3 test_app_by_producer_token.py

  deploy:
    docker:
      - image: python:3.8.1-slim-buster
    steps:
      - checkout
      - run:
          name: Deploy main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  castingapi_workflows:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
