# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  return_one_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - return 1
      - run: echo "Failed Job!"
        when: on_fail
workflows:
  # Name the workflow "welcome"
  jobs:
    - return_one_job
