"""empty message

Revision ID: 6958ee2fa5c1
Revises: d063f509e548
Create Date: 2020-11-03 20:50:51.168076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6958ee2fa5c1'
down_revision = 'd063f509e548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('actors', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('facebook_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('actors', 'phone')
    op.drop_column('actors', 'email')
    # ### end Alembic commands ###
