"""empty message

Revision ID: a2a710efcd3b
Revises: 9f7d6e6bdb5b
Create Date: 2020-11-03 17:23:24.475973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a710efcd3b'
down_revision = '9f7d6e6bdb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'body_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'driver_license',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('actors', 'ethnicity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'eye_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'hair_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('actors', 'passport',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'passport',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('actors', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actors', 'hair_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'eye_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'ethnicity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'driver_license',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('actors', 'body_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
