"""empty message

Revision ID: cd6fac5ab83e
Revises: 5fb3976c6d51
Create Date: 2020-11-04 21:49:53.165788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6fac5ab83e'
down_revision = '5fb3976c6d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'ethnicity')
    op.drop_column('actors', 'eye_color')
    op.drop_column('actors', 'hair_color')
    op.drop_column('actors', 'body_type')
    op.drop_column('roles', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('gender', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('actors', sa.Column('body_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actors', sa.Column('hair_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actors', sa.Column('eye_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actors', sa.Column('ethnicity', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
