"""empty message

Revision ID: d063f509e548
Revises: a2a710efcd3b
Create Date: 2020-11-03 18:28:43.454767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd063f509e548'
down_revision = 'a2a710efcd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'name')
    op.drop_column('actors', 'image_link')
    op.drop_column('actors', 'facebook_link')
    # ### end Alembic commands ###
