"""empty message

Revision ID: d661db1b2edb
Revises: cd6fac5ab83e
Create Date: 2020-11-04 21:50:14.580062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd661db1b2edb'
down_revision = 'cd6fac5ab83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('body_type', sa.Enum('average', 'slim', 'athletic', 'muscular', 'curvy', 'heavyset', 'plus-sized', name='body_type'), nullable=True))
    op.add_column('actors', sa.Column('ethnicity', sa.Enum('asian', 'black', 'latino', 'middle eastern', 'south asian', 'southeast asian', 'white', name='ethnicity'), nullable=True))
    op.add_column('actors', sa.Column('eye_color', sa.Enum('amber', 'blue', 'brown', 'gray', 'green', 'hazel', 'red', 'violet', name='eye_color'), nullable=True))
    op.add_column('actors', sa.Column('hair_color', sa.Enum('black', 'brown', 'blond', 'auburn', 'chestnut', 'red', 'gray', 'white', 'bald', name='hair_color'), nullable=True))
    op.add_column('roles', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'gender')
    op.drop_column('actors', 'hair_color')
    op.drop_column('actors', 'eye_color')
    op.drop_column('actors', 'ethnicity')
    op.drop_column('actors', 'body_type')
    # ### end Alembic commands ###
